title:            10个Ruby --Bob Bear
description:      A jekyll theme. Because I scribble.
url:              # Site url.
signoff:          bob bear# Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          /blog
    external:     true
  - name:         Email
    url:          mailto:bo6bear@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/bobbear
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
